// @generated by protoc-gen-es v1.2.1
// @generated from file ibc/applications/interchain_accounts/controller/v1/query.proto (package ibc.applications.interchain_accounts.controller.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { Params } from "./controller_pb.js";

/**
 * QueryInterchainAccountRequest is the request type for the Query/InterchainAccount RPC method.
 *
 * @generated from message ibc.applications.interchain_accounts.controller.v1.QueryInterchainAccountRequest
 */
export const QueryInterchainAccountRequest = proto3.makeMessageType(
  "ibc.applications.interchain_accounts.controller.v1.QueryInterchainAccountRequest",
  () => [
    { no: 1, name: "owner", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "connection_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * QueryInterchainAccountResponse the response type for the Query/InterchainAccount RPC method.
 *
 * @generated from message ibc.applications.interchain_accounts.controller.v1.QueryInterchainAccountResponse
 */
export const QueryInterchainAccountResponse = proto3.makeMessageType(
  "ibc.applications.interchain_accounts.controller.v1.QueryInterchainAccountResponse",
  () => [
    { no: 1, name: "address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * QueryParamsRequest is the request type for the Query/Params RPC method.
 *
 * @generated from message ibc.applications.interchain_accounts.controller.v1.QueryParamsRequest
 */
export const QueryParamsRequest = proto3.makeMessageType(
  "ibc.applications.interchain_accounts.controller.v1.QueryParamsRequest",
  [],
);

/**
 * QueryParamsResponse is the response type for the Query/Params RPC method.
 *
 * @generated from message ibc.applications.interchain_accounts.controller.v1.QueryParamsResponse
 */
export const QueryParamsResponse = proto3.makeMessageType(
  "ibc.applications.interchain_accounts.controller.v1.QueryParamsResponse",
  () => [
    { no: 1, name: "params", kind: "message", T: Params },
  ],
);

