// @generated by protoc-gen-es v1.2.1
// @generated from file ibc/applications/fee/v1/ack.proto (package ibc.applications.fee.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * IncentivizedAcknowledgement is the acknowledgement format to be used by applications wrapped in the fee middleware
 *
 * @generated from message ibc.applications.fee.v1.IncentivizedAcknowledgement
 */
export const IncentivizedAcknowledgement = proto3.makeMessageType(
  "ibc.applications.fee.v1.IncentivizedAcknowledgement",
  () => [
    { no: 1, name: "app_acknowledgement", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 2, name: "forward_relayer_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "underlying_app_success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

