// @generated by protoc-gen-es v1.2.1
// @generated from file ibc/applications/nft_transfer/v1/packet.proto (package ibc.applications.nft_transfer.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * NonFungibleTokenPacketData defines a struct for the packet payload
 * See NonFungibleTokenPacketData spec:
 * https://github.com/cosmos/ibc/tree/master/spec/app/ics-721-nft-transfer#data-structures
 *
 * @generated from message ibc.applications.nft_transfer.v1.NonFungibleTokenPacketData
 */
export declare class NonFungibleTokenPacketData extends Message<NonFungibleTokenPacketData> {
  /**
   * the class_id of class to be transferred
   *
   * @generated from field: string class_id = 1;
   */
  classId: string;

  /**
   * the class_uri of class to be transferred
   *
   * @generated from field: string class_uri = 2;
   */
  classUri: string;

  /**
   * the class_data of class to be transferred
   *
   * @generated from field: string class_data = 3;
   */
  classData: string;

  /**
   * the non fungible tokens to be transferred
   *
   * @generated from field: repeated string token_ids = 4;
   */
  tokenIds: string[];

  /**
   * the non fungible tokens's uri to be transferred
   *
   * @generated from field: repeated string token_uris = 5;
   */
  tokenUris: string[];

  /**
   * the non fungible tokens's data to be transferred
   *
   * @generated from field: repeated string token_data = 6;
   */
  tokenData: string[];

  /**
   * the sender address
   *
   * @generated from field: string sender = 7;
   */
  sender: string;

  /**
   * the recipient address on the destination chain
   *
   * @generated from field: string receiver = 8;
   */
  receiver: string;

  /**
   * optional memo
   *
   * @generated from field: string memo = 9;
   */
  memo: string;

  constructor(data?: PartialMessage<NonFungibleTokenPacketData>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ibc.applications.nft_transfer.v1.NonFungibleTokenPacketData";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): NonFungibleTokenPacketData;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): NonFungibleTokenPacketData;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): NonFungibleTokenPacketData;

  static equals(a: NonFungibleTokenPacketData | PlainMessage<NonFungibleTokenPacketData> | undefined, b: NonFungibleTokenPacketData | PlainMessage<NonFungibleTokenPacketData> | undefined): boolean;
}

