// @generated by protoc-gen-es v1.2.1
// @generated from file ibc/applications/nft_transfer/v1/packet.proto (package ibc.applications.nft_transfer.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * NonFungibleTokenPacketData defines a struct for the packet payload
 * See NonFungibleTokenPacketData spec:
 * https://github.com/cosmos/ibc/tree/master/spec/app/ics-721-nft-transfer#data-structures
 *
 * @generated from message ibc.applications.nft_transfer.v1.NonFungibleTokenPacketData
 */
export const NonFungibleTokenPacketData = proto3.makeMessageType(
  "ibc.applications.nft_transfer.v1.NonFungibleTokenPacketData",
  () => [
    { no: 1, name: "class_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "class_uri", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "class_data", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "token_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 5, name: "token_uris", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 6, name: "token_data", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 7, name: "sender", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "receiver", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "memo", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

